version: "3.10"

services:
  web:
    build: .
    container_name: digital_store_web
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: digital_store
